-- add_missing_customer_columns.sql

ALTER TABLE "Customer"
ADD COLUMN IF NOT EXISTS "status" VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE "Customer"
ADD COLUMN IF NOT EXISTS "pendingAmount" NUMERIC(14,2) NOT NULL DEFAULT 0;

ALTER TABLE "Customer"
ADD COLUMN IF NOT EXISTS "receivedAmount" NUMERIC(14,2) NOT NULL DEFAULT 0;

ALTER TABLE "Customer"
ADD COLUMN IF NOT EXISTS "outstandingAmount" NUMERIC(14,2) NOT NULL DEFAULT 0;

ALTER TABLE "Customer"
ADD COLUMN IF NOT EXISTS "recoveryRemark" TEXT;